In [1]:
import numpy as np
import string

In [2]:
#kodowanie gorącą jedynką 
samples=['kot siedzi na sofie','pies zjadl moje zadanie domowe']
token_index={}

for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word]=len(token_index)+1

max_lenght=10

results=np.zeros((len(samples),max_lenght,max(token_index.values())+1))
for i,sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_lenght]:
        index=token_index.get(word)
        results[i,j,index]=1
print(results)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [3]:
#kodowanie gorącą jedynką (char)
samples=['kot siedzi na sofie','pies zjadl moje zadanie domowe']
characters=string.printable #all ascii

token_index=dict(zip(characters,range(1,len(characters)+1)))

for sample in samples:
    for word in sample.split():
        if word not in token_index:
            token_index[word]=len(token_index)+1

max_lenght=50

results=np.zeros((len(samples),max_lenght,max(token_index.values())+1))
for i,sample in enumerate(samples):
    for j, character in list(enumerate(sample.split()))[:max_lenght]:
        index=token_index.get(character)
        results[i,j,index]=1
print(results)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [4]:
#keras 
from keras.preprocessing.text import Tokenizer
samples=['kot siedzi na sofie','pies zjadl moje zadanie domowe']

tokenizer=Tokenizer(num_words=1000)
tokenizer.fit_on_texts(sample)

sequences=tokenizer.texts_to_sequences(samples)
one_hot_results=tokenizer.texts_to_matrix(samples,mode='binary')

word_index=tokenizer.word_index
ans=len(word_index)

print('znaleziono %s unikatowych tokenow.' % len(word_index) )
print(f'znaleziono {ans} unikatowych tokenow.')

znaleziono 13 unikatowych tokenow.
znaleziono 13 unikatowych tokenow.


In [5]:
#haszowanie
samples=['kot siedzi na sofie','pies zjadl moje zadanie domowe']
dimensionality=1000
max_lenght=10

results=np.zeros((len(samples),max_lenght,dimensionality))

for i, sample in enumerate(samples):
    for j, word in list(enumerate(sample.split()))[:max_lenght]:
        index=abs(hash(word))%dimensionality
        results[i,j,index]=1.
